package controller;
// Generated Oct 26, 2020 8:07:52 PM by Hibernate Tools 4.3.1



/**
 * Transaksi generated by hbm2java
 */
public class Transaksi  implements java.io.Serializable {


     private Integer id;
     private int jumlah;
     private String product;
     private float total;

    public Transaksi() {
    }

    public Transaksi(int jumlah, String product, float total) {
       this.jumlah = jumlah;
       this.product = product;
       this.total = total;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getJumlah() {
        return this.jumlah;
    }
    
    public void setJumlah(int jumlah) {
        this.jumlah = jumlah;
    }
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }
    public float getTotal() {
        return this.total;
    }
    
    public void setTotal(float total) {
        this.total = total;
    }




}


